### ISSUE TITLE
How to suppress "verbose" semantic info? 

### ISSUE THREAD

**Issue by CLRafaelR** [Takeuchi-Lab-LM/python_asa#7]
@Takeuchi-Lab-LM 

Currently, I'm analyzing some transitive sentences with `python-asa`. I would like to get only argument structure information, but the returns contain unrelated (and unwanted --at least for me--) semantic information of each noun phrase. 

Suppose the case in which we typed the sentence 「太郎は次郎を追いかけた。」. It would be analysed as follows.

```
太郎は次郎を追いかけた。
4.0
[(4.0,
  {'arg': 'Arg1',
   'category': '人',
   'causative_part': 'を',
   'noun': 'スリ',
   'part': 'を',
   'passive_part': 'が',
   'semrole': '対象',
   'weight': 2.0},
  <asapy.result.Chunk.Chunk object at 0x7f9c3228c048>)]
0
[]
============================
[('状態変化なし（活動）-情報・解決策を得るための動作-追求--',
  4.0,
  [(4.0,
    {'arg': 'Arg1',
     'category': '人',
     'causative_part': 'を',
     'noun': 'スリ',
     'part': 'を',
     'passive_part': 'が',
     'semrole': '対象',
     'weight': 2.0},
    <asapy.result.Chunk.Chunk object at 0x7f9c3228c048>)]),
 ('状態変化なし（活動）-反復・継続-反復・継続-引き続く-', 0, [])]
sentence: 太郎は次郎を追いかけた。
ID: 0 太郎は
        link: 2
        type: elem
        main: 太郎
        part: は
        category: 人
        semrole: 対象
        arg: Arg1
        score: 4.0
        frame: 2-verb
        tense: PRESENT
                0       太郎    タロウ  太郎    名詞,固有名詞,人名,名                   B-PERSON
                1       は      ハ      は      助詞,係助詞                     O
ID: 1 次郎を
        link: 2
        type: elem
        main: 次郎
        part: を
        frame: 2-verb
        tense: PRESENT
                0       次      ジ      次      接頭詞,名詞接続                 O
                1       郎      ロウ    郎      名詞,一般                       O
                2       を      ヲ      を      助詞,格助詞,一般                        O
ID: 2 追いかけた。
        link: -1
        type: verb
        main: 追いかける
        part: た
        score: 4.0
        semantic: 状態変化なし（活動）-情報・解決策を得るための動作-追求--
        frame: 0-対象-Arg1,1-elem
        voice: ACTIVE
        tense: PAST
        sentelem: PREDICATE
        polarity: AFFIRMATIVE
        mood: INDICATIVE
                0       追いかけ        オイカケ        追いかける      動詞,自立       一段    連用形  O
                1       た      タ      た      助動詞  特殊・タ        基本形  O
                2       。      。      。      記号,句点                       O
elapsed_time:0.11530041694641113[sec]
```
Here, we got the information of its argument structure like:

```
sentence: 太郎は次郎を追いかけた。
ID: 0 太郎は
        link: 2
        type: elem
        main: 太郎
        part: は
        category: 人
        semrole: 対象
        arg: Arg1
        score: 4.0
        frame: 2-verb
        tense: PRESENT
                0       太郎    タロウ  太郎    名詞,固有名詞,人名,名                   B-PERSON
                1       は      ハ      は      助詞,係助詞                     O
ID: 1 次郎を
        link: 2
        type: elem
        main: 次郎
        part: を
        frame: 2-verb
        tense: PRESENT
                0       次      ジ      次      接頭詞,名詞接続                 O
                1       郎      ロウ    郎      名詞,一般                       O
                2       を      ヲ      を      助詞,格助詞,一般                        O
ID: 2 追いかけた。
        link: -1
        type: verb
        main: 追いかける
        part: た
        score: 4.0
        semantic: 状態変化なし（活動）-情報・解決策を得るための動作-追求--
        frame: 0-対象-Arg1,1-elem
        voice: ACTIVE
        tense: PAST
        sentelem: PREDICATE
        polarity: AFFIRMATIVE
        mood: INDICATIVE
                0       追いかけ        オイカケ        追いかける      動詞,自立       一段    連用形  O
                1       た      タ      た      助動詞  特殊・タ        基本形  O
                2       。      。      。      記号,句点                       O
elapsed_time:0.11530041694641113[sec]
```

However, we also received some irrelevant information on the noun phrases as follows (I'm not sure why 太郎 and 次郎 can be `'noun': 'スリ'` in this instance, too...). 

```
太郎は次郎を追いかけた。
4.0
[(4.0,
  {'arg': 'Arg1',
   'category': '人',
   'causative_part': 'を',
   'noun': 'スリ',
   'part': 'を',
   'passive_part': 'が',
   'semrole': '対象',
   'weight': 2.0},
  <asapy.result.Chunk.Chunk object at 0x7f9c3228c048>)]
0
[]
============================
[('状態変化なし（活動）-情報・解決策を得るための動作-追求--',
  4.0,
  [(4.0,
    {'arg': 'Arg1',
     'category': '人',
     'causative_part': 'を',
     'noun': 'スリ',
     'part': 'を',
     'passive_part': 'が',
     'semrole': '対象',
     'weight': 2.0},
    <asapy.result.Chunk.Chunk object at 0x7f9c3228c048>)]),
 ('状態変化なし（活動）-反復・継続-反復・継続-引き続く-', 0, [])]
```

Then, the question is how we can suppress this noun info when we put some (transitive) sentences on the command line. Any suggestions are welcome.

Thanks in advance.

**Comment by Takeuchi-Lab-LM** [comment]
Hi, CLRafaelR,

Thanks for your question. 

> I would like to get only argument structure information

You can use ASA.dumpJson() method that are defined in ASA.py and asapy.output.Output.

I attached a sample sample python program at this email. Could you put the file at asap/getpas.py. 

Let me briefly explain the idea how you can extract predicates. 
The following an example of a predicate chunk that has arguments.
> ID: 2 追いかけた。
>         link: -1
>         type: verb
>         main: 追いかける
>         part: た
>         score: 4.0
>         semantic: 状態変化なし（活動）-情報・解決策を得るための動作-追求--
>         frame: 0-対象-Arg1,1-elem
^^^^^^^^^^^^^^^^^^^
if the semantic slot is filled, the chunk must be a predicate that arguments.
The arguments are in frame slot. 
However the frame slot is a print out string in  __outputChunk() in Output.py. 
So if you need numbered arguments of each arg, you can get from this function. 

The attached program (getpas.py) uses json format that are composed in Output.py.
We are currently developing this program, then, some of the errors and insufficient outputs.

If you cannot understand Japanese and Japanese chunk-based dependency, 
let me explain chunks and arguments. 

Our predicate-argument analyzer is detecting a set of predicate-arguments based on chunk dependency.
Since dependency is not phrase, you need to follow the dependency links when you want to get a phrase.

Here is an example. The bracket [ ] indicates a chunk, and the numbers are chunk id and its head chunk id. 

[0 1 太郎の] [1 3 本を] [2 3 健が] [3 -1 捨てた]
[0 1 Taro-no]  [1 3 hon-o] [2 3 ken-ga] [3 -1 sutet-a (dumped)]

In this example, output of ASA as a predicate-aruments  is
[arg0 健が]  [arg1 本を]   [v 捨てた]  
Thus [太郎の] chunk is not extracted. If you want to get a correct phrase of arg1, i.e., 
[arg1   太郎の本を],  you have to extract [太郎の] chunk by following chunk dependency links. 

Besides, ASA is assigning semantic roles and frames according to the framefile  Predicate Thesaurus
http://pth.cl.cs.okayama-u.ac.jp/testp/pth/Vths,
ASA will miss detecting predicates that are not registered in the framefile.

Currently we estimate the accuracy of semantic role tags about 60%. It is not so high.
We did not evaluate the accuracy of just extract predicate-argument relations 
(we hope the accuracy would be  much better than semantic role labeling).

# We are increasing examples in the framefile. 

I hope this may be some help of your work.

best regards,

Koichi.

**Comment by Takeuchi-Lab-LM** [comment]
Hi 

I forgot  the attached file. Here is the sample file. I will add this to Readme in github.

best regards,

Koichi.

**Comment by CLRafaelR** [comment]
Dear Prof. Koichi Takeuchi,

I appreciate your rapid and kind reply. I will try `ASA.dumpJson()` and `asap/getpas.py` later. 
Moreover, I would like to thank you for adding English description of your programmes. 

Yours sincerely,  

Carlos Luis *Rafael* Rivera
